- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/errors.py
503 status is returned for all connection or response-related issues,
however it doesn't include the 504 responses returned by AWS ELBs for
occastional request failures. Since 504 requests should be retried
for GET requests the same way connection errors are, 504 is added
to the list of statuses that return the HTTP503Error exception.
Since HTTP503Error is a misleading name now, the exception is renamed
to `HTTPTemporaryError`.
This should fix the issues with the index-services job failing due
to 504 responses when listing the services.
> Add 504 errors to be retried together with 503 in iter_ methods

- dmapiclient/__init__.py
- dmapiclient/audit.py
- dmapiclient/data.py
- tests/test_apiclient.py
This adds a method to access the new API endpoint defined here:  https://github.com/alphagov/digitalmarketplace-api/pull/333
This PR need to be merged before the API PR, because it needs to use the new audit type defined here.
> Add method to update status of a draft

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
As per @robyoung's comment here:
alphagov/digitalmarketplace-buyer-frontend#210 (diff)
Rather than having a flag for supplier we can pass the desired user role in for authentication.
**QUESTION:** Do we actually need this `role` parameter at all now?  The login route in the buyer app is for logging in buyers or suppliers, so when do we actually need to authenticate against a specific role?  It doesn't hurt to have it here, but I'm not sure we need it.
> Role based authentication

- dmapiclient/__init__.py
- dmapiclient/api_stubs.py
- tests/test_api_stubs.py
Now that we have complex API interactions in the buyers app it would be useful to have common API response factories somewhere they can be shared between the frontend apps.
We have decided not to look at Factory Boy right now as our use case is pretty simple.
```python
api_stubs.framework(
slug="my-framework",
lots=[
api_stubs.lot(slug="my-lot", allows_brief=False)
]
)
```
> Add stubs for use in tests

- dmapiclient/__init__.py
- dmapiclient/audit.py
Used when supplier submits a brief response. Since responses are
not editable at the moment we don't need any other event types.
> Add create_brief_response audit event type

- dmapiclient/__init__.py
- dmapiclient/api_stubs.py
- dmapiclient/data.py
- tests/test_api_stubs.py
- tests/test_apiclient.py
Updated methods to match current API format for brief endpoints.
Also adds a `briefs` helper for tests.
> Update briefs client methods

- dmapiclient/__init__.py
- dmapiclient/api_stubs.py
- dmapiclient/audit.py
- dmapiclient/data.py
- tests/test_api_stubs.py
- tests/test_apiclient.py
The brief summary page looks at the last updated time, and will also show the published time for live briefs, so it's useful to have the timestamps in the `brief()` api stub helper.
Also adds a title for the brief, also for testing the brief summary page.
This also now adds an apiclient method for the delete_brief API endpoint that now exists here: https://github.com/alphagov/digitalmarketplace-api/pull/351
(But this will need to be merged first, because the API needs the new audit type introduced here.)
> Add delete brief method and add timestamps to brief stubs

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/data.py
- tests/test_apiclient.py
Now that API supports both "updated_by" and "update_details" keys
we can switch the apiclient to always send the same payload.
Adds helper methods to add user info to the request data for post,
put and delete requests.
Changes data API client methods to use the new helpers so that update
data is always sent in the same format.
Adds methods for creating, reading and listing brief responses.
> Brief responses apiclient methods

- dmapiclient/__init__.py
- dmapiclient/api_stubs.py
- dmapiclient/data.py
- tests/test_api_stubs.py
- tests/test_apiclient.py
Depends on https://github.com/alphagov/digitalmarketplace-api/pull/354
Add a method to add a clarification question to a brief.
> Add brief clarification questions

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Sets supplier framework `agreementReturned` flag to `False`.
Required to remove outdated signed framework agreements after the
original agreement document has been changed and requires a new
signature.
> Unset framework agreement returned

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Client method for the new API endpoint here: https://github.com/alphagov/digitalmarketplace-api/pull/363
> [#114474769] Add client method for new check-buyer-email API route

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Update to API client method now that the `find_briefs` endpoint can filter on status, lot and framework.
Also adds an iterator method for getting briefs, as brief fetches are paginated.
> Additional parameters for find_briefs method (status, lot and framework)

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Calls the related API endpoint and returns True if supplier is
eligible to respond to a brief or False otherwise.
Can be used to check whether "Apply" buttons should be displayed
or show an error page to the user, doesn't store anything in the
API.
> Add is_supplier_eligible_for_brief DataAPIClient method

- dmapiclient/__init__.py
- dmapiclient/api_stubs.py
- tests/test_api_stubs.py
Helpful for displaying an error message when a supplier is not eligible for a brief (currently being worked on [here](https://github.com/alphagov/digitalmarketplace-supplier-frontend/tree/ensure-eligible-suppliers)).
> Add `frameworkName` to brief stub

- dmapiclient/__init__.py
- dmapiclient/audit.py
I have chosen to go with `create_framework` rather than `framework_create` because that is how most of the other audit events are named.
> Add audit event for create_framework

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Updated register_framework_agreement_returned method to take an optional signer_details parameter. If parameter is provided then signer_details will be set/updated. If parameter is not provided then signer_details is left unchanged. Tests added for both of these cases.
Added register_framework_agreement_countersigned method with corresponding test.
We decided not to alter the signer_details field by default when calling `register_framework_agreement_returned` method because silently overwriting it by default would be surprising behaviour.
Removed previous unset_framework_agreement_returned method which is no longer being used and therefore not needed. Therefore bumped version to 4.0.0
> Added and updated methods for signerDetails and countersigned field for framework interest

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
We are expanding the scope of what the `*_details` JSON field will store to do with signing framework agreements.  (For example, not all stored values will be about the supplier who signs it -- we are also planning to save the name/role of the countersigner.)
With this in mind, we are generalising the name of the column in the database.  This is easy to do now because no one is using it yet.
We used them for DOS, so @allait says keep them in.
> `signer_details` -> `agreement_details` + un-remove unsetting framework agreements

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Added `update_supplier_framework_agreement_details` function to set and update keys in `agreementDetails`
Changed `register_framework_agreement_returned` from taking an optional `agreement_details` parameter to taking an optional `uploader_user_id` paramater. This is because when returning an agreement (that has a framework agreement version), we expect only an `uploader_user_id` instead 
of a flexible dictionary and have made this method stricter to enforce/strongly encourage this. There should currently be no usage of this in our applications as this feature is not yet released and is being tweaked since the previous related [pull request](https://github.com/alphagov/digitalmarketplace-apiclient/pull/27).
Due to the above breaking change, we bump to 5.0.0.
This PR relies on the …
> Return framework agreement and update `agreementDetails`

- dmapiclient/__init__.py
- dmapiclient/audit.py
Events created  when the user uploads a new agreement file (event created by the supplier frontend), updates agreement details (like signer details) or sets "agreement returned".
> Add audit event types for submitting signed framework agreement

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
For [this ](https://www.pivotaltracker.com/story/show/123706751) story on Pivotal.
This PR adds a new flag to the find_briefs route. This is invoked by the buyer frontend when getting a list of briefs for the catalogue.
The human flag is passed to the API to make it return a list of briefs sorted in a human readable way. PR on the API can be found [here](https://github.com/alphagov/digitalmarketplace-api/pull/422)
> Specialist briefs can be open for 1 or 2 weeks.

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
- Relies on [the API pull request](url) to be merged first.
- Breaking change, bumps version to 6.0.0
- Functionality to update a brief's status to a requested value has been deprecated in the API. A `publish` route has been added to the API, which updates the brief's status from 'draft' to 'live', that should be used instead. We have therefore removed the clients `update_brief_status` method and added a `publish_brief` method to enable this transition.
- Note, whilst a `withdraw` route has also been added to the API, we are not yet adding that to the client as this route should not be used in any of our front end apps. Withdrawing functionality is not yet being given to users and instead developers will directly curl the API to withdraw an opportunity.
> Remove `update_brief_status' method and add `publish_brief` method

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Part of [this](https://www.pivotaltracker.com/story/show/124104161) Pivotal story.
It replaces [this](https://github.com/alphagov/digitalmarketplace-apiclient/pull/32) PR from a previous version.
These updates are to allow the admin app to request briefs from the API with their user information, and to request users are filtered by `role == 'buyer'`.
> Add only_buyers and with_users to /users and /briefs respectively

- dmapiclient/__init__.py
- dmapiclient/base.py
- tests/test_apiclient.py
API responses always return next/prev links with https:// since API doesn't know if the request was made internally or through nginx. This means that apps using `_iter` methods will try to request `page=2` from `https://...`, which doesn't work when accessing the API apache server directly.
To fix this we make `_request` always use `base_url` host and scheme.
> Preserve base URL host and scheme when requesting next API page

- dmapiclient/__init__.py
- dmapiclient/audit.py
We need audit events to track creating, updating, signing, and countersigning an agreement.
> Add agreement-related audit events

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
To support temporary API route from [this pull request](https://github.com/alphagov/digitalmarketplace-api/pull/461). Can be removed after one off framework agreement countersigning script has been run.
> Temporary route to support countersigning framework agreement script

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Part of this [story in Pivotal](https://www.pivotaltracker.com/story/show/128842457).
When a CCS admin hits the button in the admin app to put an agreement on hold, the app needs to hit the api to record this change. This route on the apiclient hits the endpoint on the api that does this, passing the current user with it for an audit event.
> Add route for putting agreements on hold

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
This route only existed for a script. Now it's been run so we can remove it.
> Remove temporary route to set countersigned timestamp

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Part of (this story on Pivotal)[https://www.pivotaltracker.com/story/show/128842457].
The admin frontend needs to be able to mark `framework_agreements` as countersigned. There's a new route on the API (PR is (here)[https://github.com/alphagov/digitalmarketplace-api/pull/466]) to deal with this.
This route on the apiclient hooks the two together.
It may need updating in future depending on how the `countersigned_agreement_path` is going to be set.
> Add countersign agreement route

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Part of [this story on Pivotal](https://www.pivotaltracker.com/story/show/128842457).
When countersigning agreements, the id of the admin who clicked the button to approve agreement needs to be recorded. This updates the relevant routes on the client to accept this id and sent it through to the api.
> Send user id when countersigning framework agreements

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
All API calls should have a top level key that represents the object that is being changed. We had forgotten the 'agreement' key and had been sending the framework agreement data in the top level so this has been fixed to be consistent with the rest of our app.
See related [API pull request](https://github.com/alphagov/digitalmarketplace-api/pull/472).
> Add 'agreement' key to expected json data to approve an agreement

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
~~Forthcoming~~ [This pull request on the API](https://github.com/alphagov/digitalmarketplace-api/pull/474) adds filtering by status to the list framework agreements endpoint.  
This adds functionality to the API client to be able to pass a status parameter in.
> Filter agreements by status

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Ash has asked for a list of BriefResponses as part of [the recurring data story](https://www.pivotaltracker.com/story/show/131078097).
This pull request adds the needed `iter` method, a test for it, and a test that we were missing.
> Iterate through brief-responses

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Similar to how is done for creating a brief.
We will therefore be able to validate certain questions when creating a brief response (rather than having to validate all of them or not validating any of them).
> Send back page questions when creating a brief response

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Part of this story on Pivotal [https://www.pivotaltracker.com/story/show/129843611](https://www.pivotaltracker.com/story/show/129843611)
The new flow for brief_responses on the supplier frontend needs to be able to send updates to brief_responses to the api. This adds a route on the client to allow it.
> Update brief response route

- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/exceptions.py
- tests/test_apiclient.py
Fix crash on status URI when some API is not actually configured in the environment.
> Throwing if particular API client is not configured.

- dmapiclient/__init__.py
- dmapiclient/api_stubs.py
- tests/test_api_stubs.py
closed briefs have a publishedAt date too and we are using that to decide which flow to use for things now, this should make those tests easier and fix existing tests that run over old flows.
> adding publishedAt to the brief stub when status is closed

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Story https://www.pivotaltracker.com/story/show/134795163
kwarg defaulting to `None` to which omits url parameter (uses server's default).
> [#134795163]get_supplier_frameworks: add with_declarations support

- dmapiclient/data.py
- tests/test_apiclient.py
Now that we have a better way of doing data migrations onto local dev machines, we can obliterate the supplier/service import routes.
The only place these methods are used is in the import script found in the API. A subsequent pull request on the API will remove the script as well as the routes that actually do the imports.
> Kill the import_* wrapper methods

- .travis.yml
- requirements.txt
- setup.cfg
- setup.py
Remove `tests/*__init__.py` files to avoid tests being added by `find_packages` in `setup.py`.
Explained in depth here:
https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1cQFNx4WEvI-IGZ1g9K8JtZfeplrEmoJbtBOOpaJSEdQ
> NO-TICKET-specify-packages

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Story https://www.pivotaltracker.com/story/show/138323337
Need I say much more? Uses a separate method from `set_framework_result`.
> [#138323337]add set_supplier_framework_prefill_declaration

- dmapiclient/__init__.py
- dmapiclient/audit.py
Part of this story on Pivital [https://www.pivotaltracker.com/story/show/137359003](https://www.pivotaltracker.com/story/show/137359003)
Draft DOS1 briefs need to be migrated to become draft DOS2 briefs when
DOS1 closes and DOS2 opens. An audit event of this would be nice.
This PR [https://github.com/alphagov/digitalmarketplace-api/pull/534](https://github.com/alphagov/digitalmarketplace-api/pull/534) on the API is for the migration which does this, and it now includes creating audit events for each record updated. This new audit type is used here.
> Add audit event for updating a briefs framework id

- dmapiclient/__init__.py
- setup.py
enum34 1.1.2 failed to install on Python 3.6, so I'm bumping it to
the latest version (1.1.6) which has a pre-built wheel.
> Fix enum34 install error on Python 3.6

- dmapiclient/__init__.py
- dmapiclient/search.py
- tests/test_apiclient.py
Implements support for the search-api's `aggregations` endpoint.
Bump version to 8.10.0
https://trello.com/c/5LRAkydD/481-show-number-of-services-within-category
> Add aggregations method to search api client

- dmapiclient/__init__.py
- setup.py
This is needed because `enum34` won't work on python >= 3.4.
The trick used is directly from the `enum_compat` python package (the advantage over just using that is retaining finer control over versions).
> only conditionally depend on enum34 (if python < 3.4)

- dmapiclient/__init__.py
- dmapiclient/errors.py
- tests/test_apiclient.py
Previously, it was only 503 or 504 errors would cause the `find_{model}_iter` function to retry the failing call. Now we've added 502 errors as well.
This is to mitigate a problem we're experiencing with exporting brief responses.  It's happened a few times that the `find_brief_responses_iter` function gets through about ~190 pages of brief responses and then fails upon getting back a 502 error.
Manually testing getting back brief responses fails intermittently but not reliably so we're going to make the API client more resilient while we're investigating the problem.
This is a short-term-type solution so that we can complete the data exports, but it doesn't actually do anything to address the failures in the API.
> Try again when getting back 502 errors

- .gitignore
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
This is part of a story to tell interested suppliers that a question has been answered.
Related dm-api pull request: https://github.com/alphagov/digitalmarketplace-api/pull/614
Trello ticket: https://trello.com/c/2noI0EFB/472-tell-interested-suppliers-that-a-question-has-been-answered
> Add 'with_clarification_questions' parameter to `find_briefs`

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Ticket: https://trello.com/c/kGVfzXuH/749-3-collect-award-status-on-buyer-dashboard
PR 2 of 4 - API client
See also:
PR 1 of 4: API: https://github.com/alphagov/digitalmarketplace-api/pull/622
PR 3 of 4: Question content: https://github.com/alphagov/digitalmarketplace-frameworks/pull/464
PR 4 of 4: Briefs front end: https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/12
Introduces two new data API client methods: `update_brief_award_brief_response` (for updating the winning BriefResponse) and `update_brief_award_details` (for updating contract details).
> Data API client methods for awarding brief_response + award details

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/search.py
- tests/test_apiclient.py
We are removing the default index name from the Search API Client and requiring it to be passed explicitly. This is because we are moving away from a single index called 'g-cloud' and moving towards an index-per-framework where the index name is the framework slug. Given this, we can get the index name programmatically and don't need to statically define it anywhere.
Bump version to 9.0.0
Required work under https://trello.com/c/Hlq5mzAy/619-save-a-search-and-create-a-project
> Remove default index from searchapiclient

- dmapiclient/__init__.py
- dmapiclient/audit.py
- dmapiclient/base.py
- dmapiclient/data.py
- dmapiclient/search.py
- tests/test_apiclient.py
Add APIClient methods for interacting with Direct Award projects on the API. Adds methods on the Search API client to generate the full search-api URL that a given call will hit. This is stored by the API for Project searches.
This PR also wraps the `register_uri` function of the rmock and inserts the `complete_qs` parameter, if not supplied. This forces the URLs to match exactly; without it, missing query params would not trigger a failed test case. A couple of tests broke from this change, so fixed those up to properly mock the full URL.
API: https://github.com/alphagov/digitalmarketplace-api/pull/624
Buyer FE: https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/581 (for trying out the flow only; not for review yet) …
> Direct Award Projects

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Update api client to use adjusted query params, JSON formats, etc for Direct Award based on feedback from code review. Query params = snake case, JSON data = camel case.
Bump version to 9.1.1
> update apiclient for updated api parameter formats

- dmapiclient/__init__.py
- dmapiclient/search.py
- tests/test_apiclient.py
* Adding a new method to turn the search api url into frontend url
* Bump version to 9.2.0
* Also found a bug with two previously implemented methods for getting search/aggregation URLs whereby it would include the `q` parameter by default if not supplied. Made sure this doesn't happen and pinned it with two tests.
https://trello.com/c/Hlq5mzAy/619-save-a-search-and-create-a-project
> Save a search and create a project

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
`user-id` was being passed to the `get_direct_award_project` endpoint, but the API just ignores this. So let's remove it. And bump version to 10.0.0
> Remove unused param from get_direct_award_project

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_apiclient.py
Trello ticket: https://trello.com/c/ggDGUY5d/823-2-collect-status-when-a-buyer-is-not-proceeding-with-an-award-no-journey-backend
New API client methods to pass the new `cancelled` and `unsuccessful` statuses to the same existing API route `update_brief_status` (which at present just accepts `publish` and `withdraw` - this will be changed in the API very shortly!).
> Update Brief status to cancelled or unsuccessful

- dmapiclient/__init__.py
- dmapiclient/search.py
- tests/test_apiclient.py
To display the search overview page correctly we need to know what framework instance the search relates do. We know this from the search API URL which includes the framework slug. Therefore, we need to be able to extract the slug from the API URL. This adds a method on the search API client to do this.
Bumps version to 10.2.0.
https://trello.com/c/9YtT8DmX/675-task-list-saved-search-overview-page
> Get index from search api url

- dmapiclient/__init__.py
- dmapiclient/audit.py
- dmapiclient/data.py
- dmapiclient/search.py
- tests/test_apiclient.py
Adds a new method to the DataAPIClient to lock a Direct Award Project, and a new method (+ `_iter`) to the SearchAPIClient to retrieve services from a given Search API URL.
Bumps the version to 10.3.0
https://trello.com/c/gs2I3Cj2/676-end-your-search
> Lock projects and get all services by Search API URL

- dmapiclient/__init__.py
- dmapiclient/search.py
- tests/test_apiclient.py
When we lock Direct Award projects (at the 'end search' stage), we need to record all the service IDs that matched for the given search.
Bump version to 10.5.0.
Remove some 'helper' functions that exist for no real reason (get_search_url/get_aggregations_url)
https://trello.com/c/gs2I3Cj2/676-end-your-search
> Add "IDs only" option to search services

- dmapiclient/__init__.py
- dmapiclient/data.py
- dmapiclient/search.py
- tests/test_apiclient.py
Retrieve only active searches from a direct award project. At the moment we enforce only one search active at a time, but given this is a common usecase it is still useful to have a way of only returning the active search as all frontend calls just ignore inactive searches at the moment.
Add back in that get_search_url method that I thought was useless but was obviously part of a public interface.
Bump version to 10.6.0.
https://trello.com/c/igRhA3Bt/711-shortlist-file-download
> Support only-active parameter for list searches endpoint

- dmapiclient/__init__.py
- dmapiclient/audit.py
- dmapiclient/data.py
- tests/test_apiclient.py
Implements the apiclient methods to get Direct Award Project services and to record the download of search results.
Adds a new AuditEvent type for downloading search results.
Bumps the version to 10.7.0.
https://github.com/alphagov/digitalmarketplace-api/pull/656
https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/615
https://github.com/alphagov/digitalmarketplace-utils/pull/332
https://github.com/alphagov/digitalmarketplace-frameworks/pull/473
https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/32
https://trello.com/c/igRhA3Bt/711-shortlist-file-download
> Get Direct Award Project services

- tests/conftest.py
- tests/test_base_api_client.py
- tests/test_data_api_client.py
- tests/test_search_api_client.py
@katstevens Meant to comment about this on the PR but was too late. To make a fixture available to all tests just stick it in the `conftest.py`
https://docs.pytest.org/en/latest/fixture.html#sharing-a-fixture-across-tests-in-a-module-or-class-session
> Deduplicate test fixture rmock into conftest file

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
For consistency with our other model creation endpoints.
See API changes here: https://github.com/alphagov/digitalmarketplace-api/pull/674/commits/c91f0630462b33fc40b9cbf3b97e2ab1459ad7f4
> Buyer Email Domain URL should be pluralised

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
For this ticket: https://trello.com/c/eo8gJE4C
The serialize method for direct award projects has a `with-users`
parameter.
There is a PR up on the api to allow the `list_projects`
endpoint to accept `with-users` as a param
The endpoints on the API for direct award searches and services take an
optional `user-id` param.
The apiclient forced you to supply one. This made getting all searches
or services for a given project difficult.
The `make_iter_method` method expects its second argument to be the name
of the model as returned in a serialized blob. For
direct_award_project_searches this is 'searches' and not 'projects'.
> Update for saved search data tracking

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Required for Trello ticket https://trello.com/c/7kq7pSTr/83-allow-buyers-withdraw-open-opportunities
I guess we've never had to do this via the API client before! It simply follows the pattern for the `cancel_brief` method, which calls the same API endpoint (but with `withdraw` instead of `cancel`).
> Withdraw brief method

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Following expansion of callable brief parameters on API
> Add closed_on and withdrawn_on parameters to find_briefs method

- dmapiclient/__init__.py
- dmapiclient/audit.py
- dmapiclient/data.py
- setup.cfg
- tests/test_data_api_client.py
Part of this ticket: https://trello.com/c/DbYlqSxv/121-exclude-changes-made-by-admin-in-the-approve-edits-section
We need a new audit type to be able to easily distinguish edits by admins from edits by suppliers.
We need the API to take an additional (optional) parameter so it knows which type of audit event to use.
> Add new update-by-admin audit event type

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/search.py
- tests/test_search_api_client.py
Minor - not backward-compatible - change to the search API client, to account for the new `mapping` argument that is shortly arriving in the Search API. See <https://github.com/alphagov/digitalmarketplace-search-api/pull/115>.
https://trello.com/c/5oIKvS1s/100-search-service-for-briefs-plus-indexing-script
> New `mapping` parameter for index creation.

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
https://trello.com/c/2Uc2WMl2/155-allow-super-admin-invite-new-admin-users
https://docs.google.com/document/d/1MjvYx9aQWgcbryiaGrRLOPt_lVm8gIbqOH3vmkKx_fo/edit#
For this new page we agreed to restrict email addresses that can be invited to become an admin by domains listed in the app config.
* New apiclient method using new api end point
* Tests
> 155 allow admin manager invite new admin users

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
This was done to enable editing admin user name as per this ticket:
https://trello.com/c/j1jx6KkX/154-allow-super-admin-edit-admin-roles
> Add name parameter to 'update_user' method

- dmapiclient/__init__.py
- setup.py
Upgrades `requests` to address a potential vulnerability: https://snyk.io/vuln/SNYK-PYTHON-REQUESTS-40470
The following repos will need their version of the API client bumped to pull in the update:
- API
- Admin FE
- Briefs FE
- Brief Responses FE
- Buyer FE
- Scripts
- Supplier FE
- User FE
Repos already upgraded:
- Search API
- AWS
- Cloudwatch to Graphite
> Upgrade Python requests package

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/search.py
- tests/test_search_api_client.py
Part of this ticket: https://trello.com/c/KcqU7k20
We want to be able to search for more than just services. Allowing
doc_type to be passed some functions will allow this. Setting the
default to `services` will maintain some backwards compatibility
This is really similar to `search_services`. The only reason for not
combining them is for backwards compatability. It may be something we
want to do.
We want to aggregate briefs as well as services now. I would have
created a new method `aggregate_briefs` to prevent the breaking change,
but this method is used by helper methods in the frontend and so needs
to be general.
> Search and aggregate briefs

- dmapiclient/__init__.py
- dmapiclient/base.py
- tests/test_data_api_client.py
As part of a PR to standardise the API responses (
alphagov/digitalmarketplace-api#693), we
may no longer be including `links` dicts as part of an endpoints
response.
An endpoint may change from returning a `paginated_result_response`
to returning a `list_result_response` based on the query params
that have been provided.
We discovered that we have iter methods such as the
`find_services_iter` which will break when passing in a supplier
ID paramater as they now return a standardised `list_result_response`
which no longer includes `links`. However the `iter` methods at
the moment rely on getting a `links` key in their result.
Changing our API client to be permissive feels like the easiest
thing to do which won't have any functionality changes, especially
as it is likely that we were only …
> Allow iter methods to not find `links` key in JSON response

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
`awarded_at` can now be passed into the api as a date in the form of `YYY-MM-DD`.
Merge after:
https://trello.com/c/LsEbL3jP
> Filter brief responses by awarded_at date

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
We can already filter Briefs by these date fields on the API route. This PR just adds the kwargs to the API client method. 
Usage:
```
result = data_client.find_briefs(cancelled_on="2017-10-20")
result = data_client.find_briefs(unsuccessful_on="2017-10-20")
```
> Filter Briefs by unusccessful_on and cancelled_on dates

- dmapiclient/__init__.py
- dmapiclient/api_stubs.py
- tests/test_api_stubs.py
Add a fixture for supplier data from the API to help test the additions to the framework application tasklist.
https://trello.com/c/8Ahl8YNc/43-supplier-account-add-supplier-details-to-tasklist-page
> Add fixture for supplier data from api

- CHANGELOG.md
- dmapiclient/data.py
- tests/test_data_api_client.py
Remove get_direct_award_project_services_iter in favour of find_x equivalent; fix some tests to use _test_find_iter correctly
https://trello.com/c/QV36xkLW/216-getmodeliter-v-findmodeliter-in-the-apiclient
> Rename method, fix tests

- dmapiclient/api_stubs.py
- tests/test_api_stubs.py
Registration date is a field we are no longer interested in, so we should remove all references from it as we will be dropping it from the API shortly.
https://trello.com/c/M2jPJ3kZ/58-purge-registration-date-from-logic-and-data
> Remove registration date

- dmapiclient/__init__.py
- dmapiclient/base.py
- tests/test_data_api_client.py
...however still fall back to using `request.request_id` failing that for compatibility: I *think* I've upgraded the `-utils` on all the relevant apps but could have missed something, so playing safe.
Strikes me that there isn't really any sort of integration test for this functionality - checking that a header makes it all the way through. Not sure where such a thing would live.
Trello https://trello.com/c/exuNFb7A/357-zipkin-headers-pt2-api-client , part of the broader https://trello.com/c/UOXf4vZZ/308-make-use-of-zipkin-headers-in-preference-to-request-id
> request id handling: switch to using request.get_onwards_request_headers if available

- CHANGELOG.md
- dmapiclient/__init__.py
PR #123 failed to *actually* bump the version to `15.0.0` meaning the potentially breaking change got introduced as of `14.5.0`, so here we're just quickly bumping it before that causes a problem.
> Bump version to 15.0.0

- dmapiclient/__init__.py
- dmapiclient/api_stubs.py
- tests/test_api_stubs.py
We require everyone to answer the "VAT number" question, even if just to say "No I'm not VAT registered".  So we shouldn't delete it from the fake API response here.
> Update API stubs to not delete VAT number

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Part of this trello ticket: https://trello.com/c/Nbv7N4lf
This is for calling the endpoint on the api for copying all of a
particular lots services between frameworks.
To support newer Python3 syntax through flake8 3.5.0. No per file
ignores are required currently but installing it keeps consistency with
how we use it elsewhere.
> Add method for copying all lots services

- dmapiclient/__init__.py
- dmapiclient/data.py
- dmapiclient/search.py
This fell out of a 2ndline ticket https://trello.com/c/f8SAV9WL/261-failure-of-data-export-job-overnight - turns out it's kinda annoying to look at tracebacks without "correct" function names.
This isn't a very pretty way of doing it but is the least complex way of doing it that doesn't introduce significant possibilities of wrongness.
The slightly more automatic way of doing this would involve maybe using a class decorator to do the name assignment post-declaration.
> *_iter methods: give these all correct __name__s

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Adds method for updating a framework via the apiclient. Going to be used
to update all existing frameworks with their lifecycle dates.
Bumps version to 15.3.0.
https://trello.com/c/BVPgZRZc/65-store-datetimes-relating-to-the-framework-lifecycle-on-the-api
> Update framework via data client

- dmapiclient/__init__.py
- setup.py
Our frontend apps all depend on Flask v0.10.1 specifically, but this
repository doesn't. Flask released v1.0.0 over the weekend and this is
trying to pull it in now, which breaks things. Let's pin this dependency
to the specific version and review if/how/when/whether we should upgrade
to Flask v1.0.0
> Pin to Flask==0.10.1

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Trello: https://trello.com/c/gVkJo8Zj/70-update-framework-manager-user-download-list-to-include-additional-fields
Adds a new method to call the new Supplier export route on the API (see branch in progress: https://github.com/alphagov/digitalmarketplace-api/compare/178-update-framework-manager-user-download-list-to-include-additional-fields-ver-2).
> New DataAPIClient method for supplier export route

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
https://github.com/alphagov/digitalmarketplace-api/pull/802
This PR:
* Bumps the version
* Adds a new AuditType for removing the personal data from a user
* Adds methods to interact with the `remove-personal-data` user and contact information api endpoints
* Adds tests for these methods
> 208 delete users code that takes the user and strips all the personal data out

- .travis.yml
- CHANGELOG.md
- default.nix
- dmapiclient/__init__.py
- dmapiclient/base.py
- requirements-dev.txt
- tests/test_base_api_client.py
- tests/test_data_api_client.py
This required a bit of tidying & refactoring to be doable in a clear, extensible and robust way.
Also add tests for the presence/absence of this childSpanId parameter, incidentally the first tests of logging behaviour for this library.
> BaseAPIClient: add childSpanId parameter to log output

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Suppliers need to confirm that their company details are correct when
they're applying to a framework, so we need an API setter for this.
https://trello.com/c/V0FSdOCJ/188
> Set application company details

- .flake8
- requirements-dev.txt
Also replaces `flake8-putty` with `flake8-per-file-ignores`.
You might need to delete and rebuild your venv when this change hits.
> Bump flake8 to version 3.5.0

- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/data.py
- tests/test_data_api_client.py
This PR adds the apiclient method needed for the 'we are still assessing flow' [ticket].
It also adds a `_patch` method to the base api client class, so that the new PATCH endpoint from https://github.com/alphagov/digitalmarketplace-api/pull/807 can be used.
[ticket]: https://trello.com/c/5Lrp1lOK/110-fe-8-we-are-still-assessing-flow
> Add 'we are still assessing' method

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/errors.py
- tests/test_base_api_client.py
We have been getting some mystery 503s in the buyer-frontend and don't
get any useful error information from the apiclient. This update causes
the apiclient to emit more useful information via the str() and repr()
calls on the base error.
> Log more detail on request exceptions

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Add generic update method: the API's method is intended to be generic, so logically (arguably) the API Client should be fairly generic too.
Goes with https://github.com/alphagov/digitalmarketplace-api/pull/814
https://trello.com/c/7wlBbGU0/138-add-step-3-assessing-your-service-and-badges
> Add generic update method

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/errors.py
- setup.py
- tests/test_base_api_client.py
- tests/test_data_api_client.py
See [this related PR on utils to add logging for this.](https://github.com/alphagov/digitalmarketplace-utils/pull/427)
This was heavily influenced by this blog post: [https://www.peterbe.com/plog/best-practice-with-retries-with-requests](https://www.peterbe.com/plog/best-practice-with-retries-with-requests)
This will allow the api client to retry requests which raise connection
errors, read errors, as well as requests that return certain 500 error codes.
For the tests, I've had to reach quite a long way in to the requests and
urllib3 modules. This is because response_mock (rmock fixture) mocks the
adapter that requests uses. Doing this means that we never actually
retry anything. I was torn between doing this potentially quite fragile
testing method, or just testing that Retry was called …
> Add retry to base api client requests

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Trello: https://trello.com/c/1sy265Zw/495-api-client-methods-for-exportusersiter-and-exportsuppliersiter
This has been in the Quick Wins column for 6 weeks 😹 Doing this now as it'll help improve our slow requests target.
TODO: The other parts of this puzzle:
- make the API endpoints for these methods paginated
- use the new `*_iter` methods in the apps/scripts.
> Add export_users_iter and export_suppliers_iter methods

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
For [this trello ticket.](https://trello.com/c/AdtcNmBR)
See [this associated PR on the api.
](https://github.com/alphagov/digitalmarketplace-api/pull/826)
The api now accepts this parameter to filter audit events by the
supplierId field of the audit events data json blob, if it exists.
> Add data_supplier_id param to `find_audit_events`

- Makefile
- default.nix
Python36 includes the venv module which means we no longer need virtualenv to be installed on the development system
> Remove requirement on virtualenv

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
See [this closed PR ](https://github.com/alphagov/digitalmarketplace-api/pull/836)adding the endpoint to the API.
We have an new endpoint for transitioning DOS frameworks. This allows
the apiclient to call it.
> Add method for transition-dos endpoint

- dmapiclient/__init__.py
- requirements-dev.txt
- setup.py
When I rebuild the virtualenv for an app which has been updated to Flask 1.0.2, I get errors similar to:
```
digitalmarketplace-apiclient 19.0.0 has requirement Flask==0.10.1, but you'll have flask 1.0.2 which is incompatible.
```
This PR should fix this issue by pinning us to sensible version ranges for each dependency.
> Update setup.py requirements

- dmapiclient/__init__.py
- dmapiclient/base.py
- tests/test_base_api_client.py
Fell out of https://trello.com/c/aWnL8fAa/192-antivirus-create-catch-up-bulk-scan-script
Turns out we've never had timeouts set on the api client. This means requests can wait indefinitely. In the apps, it means they will continue to the point that the parent request times out the whole app request (usually it is the router that ends up doing this). In scripts it means they can hang pretty much indefinitely.
How do people feel about 45s as an initial default? I've made this a constructor argument instead of a pseudo-constant (a la `RETRIES`) because it feels we're going to want to adjust this more often.
Would people like me to add an `init_app` implementation that can pull this value from app config?
> BaseAPIClient: add a `timeout` constructor argument for controlling the timeout of connections

- dmapiclient/__init__.py
- dmapiclient/antivirus.py
- tests/test_antivirus_api_client.py
https://trello.com/c/ZSg7FK5s/201-apiclient-sort-out-timeouts-retrying-once-for-all
Following rollout of https://github.com/alphagov/digitalmarketplace-antivirus-api/pull/18 the antivirus api will accept `PUT` requests for `scan_and_tag_s3_object`'s endpoint. The reasoning is covered there.
> antivirus api: switch to sending PUT requests for scan_and_tag_s3_object 

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
This commit adds a method to the apiclient that allows a user to remove a declaration on a supplier_framework. It's implemented by calling a pre-existing method to DRY the code out as much as possible.
[Ticket](https://trello.com/c/xhq2Vy7l/211-update-apiclient-with-method-for-removing-supplierframework-declarations)
> Adds method for accessing the endpoint

- tests/test_base_api_client.py
https://trello.com/c/ZSg7FK5s/201-apiclient-sort-out-timeouts-retrying-once-for-all
In the above card I was originally planning on making some additions to the apiclient to override what methods should be considered "safe" for retries, because we know certain endpoints to be so. But that made be realize that I should perhaps instead be taking that as a hint and switching that endpoint to a non-idempotent method like `PUT`.
Anyway, in the lead-up to doing this I expanded an existing test on the apiclient, which is still useful for clarifying existing behaviour. Deliberately haven't bumped version because it doesn't matter to library consumers.
> TestBaseApiClient: test combinations of method/HttpError that aren't considered safe to retry

- dmapiclient/__init__.py
- setup.py
Add python_requires specification to setup.py that explicitly declares which versions of Python this library supports/is tested on.
Part of https://trello.com/c/wWFsv1SU/230-be-clear-in-our-libraries-what-versions-of-python-we-support
> Support Python 3.6 only

- README.md
- dmapiclient/__init__.py
Adds a nifty visual indicator of what versions of Python we support
Part of https://trello.com/c/wWFsv1SU/230-be-clear-in-our-libraries-what-versions-of-python-we-support
> Add Python badge to README

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Trello: https://trello.com/c/tZJCxC87/249-new-admin-search-box-for-suppliers
Small change, to supply an extra search parameter `company_registration_number` to the `find_suppliers` method. See https://github.com/alphagov/digitalmarketplace-api/pull/849 for details.
> Supplier search by Company registration number

- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/search.py
- setup.py
This PR is to remove uses of the `six` library. I've replaced them with their python 3 equivalents. I've also updated `setup.py` 
[Ticket](https://trello.com/c/AdmER908/149-remove-python2-deps-from-apiclient)
> Remove six library

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Trello: https://trello.com/c/aSOduJAQ/319-admin-search-for-registered-name-as-well-as-supplier-name
Allow the apps to search the API by supplier name or registered name. See https://github.com/alphagov/digitalmarketplace-api/pull/859 for details.
Tested this locally with the Admin FE.
> Add name keyword to find_suppliers

- requirements-dev.txt
Supersedes the current open PyUp PRs for this repo.
`flake8` now supports per-file-ignores well enough for our purposes. This means we can remove the extra `flake8-per-file-ignores` dependency.
> Update test dependencies

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/data.py
https://trello.com/c/N6rdL6nQ/416-findframeworksuppliers-api-view-and-api-client-method-differ-on-withdeclarations-param
> find_framework_suppliers default change

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
We've had a request from CCS to see the list of approved email address domains for buyers (https://trello.com/c/h0CbxA9t/754-domain-whitelist-for-buyers). In future we might also want to add an admin frontend view that displays this info (https://trello.com/c/4LinvI5X/810-allow-admin-framework-manager-to-view-list-of-trusted-buyer-email-domains).
This commit adds a method to grab a page from the `/buyer-email-domains api endpoint`, and also an iter method so that you can easily fetch all values in one go.
> Add get_buyer_email_domains methods

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
https://trello.com/c/V7cUDIRW
All for the purpose of being able to _set_ this flag, yup, need a new apiclient method.
> DataAPIClient: add set_supplier_framework_allow_declaration_reuse

- CHANGELOG.md
- default.nix
- dmapiclient/__init__.py
- dmapiclient/antivirus.py
- dmapiclient/base.py
- dmapiclient/data.py
- dmapiclient/search.py
- tests/test_base_api_client.py
- tests/test_search_api_client.py
God knows where the ticket for this is if it ever had one - it's been kicking around for a while.
This is to encourage immutabile use of api clients after construction/init_app, which should provide more threadsafety.
> BaseAPIClient: make writeable attributes private

- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/data.py
- dmapiclient/search.py
- tests/test_base_api_client.py
- tests/test_data_api_client.py
- tests/test_search_api_client.py
This is a part of a potential way of addressing https://trello.com/c/LABe8BKA
The pattern it introduces is something I like to call async-not-async. It's simply allows a user of the `apiclient` to perform a highly simplified form of async http request by ignoring the response from the server. It does this by setting the read timeout to something tiny and allowing that timeout to happen. It relies on the fact that web server stacks tend not to readily propagate "the client is gone" information, and a request will continue to be processed fully, even after the client has given up.
In the case we're proposing to use it it gives us basically all the advantages of true async but also all the perils: how easy it is to launch hundreds of requests in a couple of milliseconds without considering …
> add client_wait_for_response option to some method calls

- dmapiclient/__init__.py
- dmapiclient/data.py
- dmapiclient/search.py
- tests/test_data_api_client.py
- tests/test_search_api_client.py
When attempting to implement https://trello.com/c/LABe8BKA it would be helpful to add these options to the actual api calls that the admin view in question uses in the first place.
So add `wait_for_index` option to `DataApiClient.update_service_status()`.
Also since the api's view corresponding to `update_service_status` can also _delete_ items from the index, using `SearchAPIClient.delete()`, we need to add the `client_wait_for_response` argument to _it_.
> add more client_wait_for_response, wait_for_index options

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
https://trello.com/c/2FBIg5LP
Didn't give this a default in the end.
> DataAPIClient.find_brief_responses(): add with_data parameter

- dmapiclient/__init__.py
- setup.py
https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
The ~= syntax denotes we don't fully support higher versions yet:
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
See equivalent PR for utils: https://github.com/alphagov/digitalmarketplace-utils/pull/544
> Remove upper restriction on Python versions

- .travis.yml
- requirements-dev.txt
https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
- Bumps test utils to bring in 3.7+ support
- No code changes so not bothering with a version bump
> Enable Travis checks for Python 3.7 and 3.8

- dmapiclient/__init__.py
- dmapiclient/audit.py
https://trello.com/c/mLU7vty9/1343-inconsistency-with-supplier-on-the-dos4-framework-amaze-realize
A new audit event type will be needed to link two supplier IDs on the same audit event.
> Add new AuditType for updating the supplier on a service

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
This updates the API client to use the methods introduced in https://github.com/alphagov/digitalmarketplace-api/pull/1037
> use POST email address methods

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
This already exists in the API. I want to be able to create frameworks via the API client, though.
> Add create_framework method

- .secrets.baseline
- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/data.py
- tests/test_data_api_client.py
This is mainly meant as a quality-of-life improvement for devs using the API client shell in digitalmarketplace-scripts; instead of having to remember to add `updater` or `user` to each method call and typing their email address every time, they can now set it once when constructing the API client object. It might also help with simplifying writing scripts.
This commit adds a new property to BaseApiClient, `_user`, which can be `None` or a string. If it is a string this will be used for `updated_by` when using a method that makes a change using the API. The caller can still use the user argument for the method call if they want to, and this will supersede the value of the property, but now they don't have to. If they haven't provided the argument in the method call or set the property, a …
> Add default `updated_by` property to BaseApiClient

- dmapiclient/__init__.py
- dmapiclient/data.py
Some API endpoints are paginated and some are not. But there also exist three that may be paginated depending on the request parameters. This last category is rather confusing, so document them.
> Document responses that are sometimes paginated

- requirements-dev.txt
We want to install digitalmarketplace-test-utils from PyPI instead of VCS, so we can rely on Dependabot to update our apps automatically when a new version is available.
> Bump digitalmarketplace-test-utils from git to PyPI

- dmapiclient/__init__.py
- dmapiclient/data.py
- dmapiclient/search.py
The paginated methods are dangerous. It's not obvious without reading the source that they are paginated, so it's very easy to write scripts that will fail when the number of API object it's operating on becomes large. In scripts, you almost never want pagination.
Most paginated methods also have a non-paginated '_iter' alternative that is much safer. Deprecate the paginated versions. Pycharm will now warn about uses of the deprecated methods. You can still use the methods - you'll just get a warning.
We've been bitten a few times recently by accidentally using paginated API methods inappropriately. This should hopefully make that sort of mistake less common in future.
> Deprecate paginated methods with an alternative

- dmapiclient/__init__.py
- dmapiclient/errors.py
https://trello.com/c/9RUq5TL8/1243-2-bug-emessage-passed-to-inappropriate-error-handler
The types are not as expected, which has caught people out before. Hopefully adding type hints will make the behaviour less surprising in future.
> Add type hints to APIError methods

- .github/workflows/publish.yml
- .github/workflows/release.yml
- setup.py
Ticket: https://trello.com/c/R6jfWwZh/2175-use-github-actions-to-publish-packages-to-pypi
This commit adds two workflows to replace [our current Jenkins job to tag new versions of this package][1], and also adds a new [`digitalmarketplace-apiclient` PyPI package][2].
The hope is that by uploading packages to PyPI we will be able to get Dependabot to manage our library versions across our apps, and save us a lot of work updating packages.
[1]: https://ci.marketplace.team/job/tag-dmapiclient/
[2]: https://pypi.org/project/digitalmarketplace-apiclient/
> Add GitHub workflows to release and publish package

- dmapiclient/__init__.py
- dmapiclient/audit.py
https://govuk.zendesk.com/agent/tickets/4475776
We're going to add a new API endpoint to allow us to delete domains from the buyer allow list. So we need a new audit event type.
> Add delete_buyer_email_domain audit event type

- CHANGELOG.md
- dmapiclient/__init__.py
- dmapiclient/base.py
- dmapiclient/errors.py
- dmapiclient/search.py
- mypy.ini
- requirements-dev.in
- requirements-dev.txt
- setup.py
- tasks.py
Use mypy to check the types in this library. Then mark the library as having type hints so consumers can use them.
Note that the type hinting is thus far rather sparse, so this will not yet be very useful to consumers.
Copied very heavily from https://github.com/alphagov/digitalmarketplace-utils/pull/606
> Add type hint checking

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
https://trello.com/c/FGm8bi13/3-2-suppliers-may-be-missing-out-on-opportunities-due-to-misleading-banner
There are 18 possible status_date_filters, so we don't want to add them all individually. Instead allow users to provide a dictionary and let the API work out whether it's correct or not.
This should make a spot of analysis I'm trying to do a bit easier.
> Add support for status_date_filters to find_briefs

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
It's something we often do in scripts. I've just added support for it in the API (https://github.com/Crown-Commercial-Service/digitalmarketplace-api/pull/1191).
And update tests accordingly
> Add support for listing active users

- dmapiclient/__init__.py
- dmapiclient/data.py
- tests/test_data_api_client.py
Add a new method to the api client to allow it to undo the countersigning of the framework agreement. This should only need to be used once and then we may consider removing it.
I have added tests for this new method.
> Add a new method to the api client to allow it to undo the countersigning
