dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
Implements: alphagov/digitalmarketplace-api#315
Bumps version to: **`1.1.0`**
=> Add parameter to order audit events

dmapiclient/__init__.py, dmapiclient/audit.py
This is required for creating and updating a brief.
[#111139752](https://www.pivotaltracker.com/story/show/111139752)
=> Add brief audit events

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
Add methods to get, create, update, list and update the status of briefs.
=> Add brief apiclient methods

dmapiclient/__init__.py, dmapiclient/api_stubs.py, tests/test_api_stubs.py
Includes fields that are autogenerated when a brief is published.
=> Update brief stub

LICENCE
Add a copy of MIT license file with a current copyright year
=> Add MIT license file

dmapiclient/__init__.py, dmapiclient/base.py, dmapiclient/data.py
which was already supported by API but not exposed here. Bump to 3.8.0
=> find_services: add lot parameter

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
Story https://www.pivotaltracker.com/story/show/127806845
Need I say more?
=> [#127806845]add agree_framework_variation api method to data api client

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
To match changes agreed with @risicle on this API PR:
=> Pluralise agreed variations

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
Following further changes here:
(Will wait for that to go in before merging the API client this time.)
=> Put after all

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
Add routes to get and update a framework agreement
=> Bump version to 6.5.0

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
Add routes to create and sign a framework agreement.
=> Add remaining framework agreement routes

dmapiclient/__init__.py, dmapiclient/audit.py
Part of [this story on Pivotal](https://www.pivotaltracker.com/story/show/129838783).
New audit types are needed for the new supplier multipage flow for applying to briefs.
=> New audit events for brief responses

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
For the API filtering a brief response by status (found in [this API pull request](https://github.com/alphagov/digitalmarketplace-api/pull/482))
=> Filter brief response by status

CHANGELOG.md, dmapiclient/__init__.py
- Updated the changelog as technically this is a breaking change
- Fixed a tiny link text issue
- Added syntax highlighting to code samples in the changelog
=> Bump version after removing import routes

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
* remove `find_frameworks_iter` (never used, broken)
* add `find_supplier_declarations`
* version bump
* test
=> 138323285-rm_find_frameworks_iter__add_find_supplier_declarations

dmapiclient/__init__.py, dmapiclient/api_stubs.py
I needed to create some DOS2 frameworks for testing out the work done in [this PR](https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/439) on the buyer frontend.
=> Add dos2 to api stubs

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
Story https://www.pivotaltracker.com/story/show/141299531
What more can I say?
=> [#141299531]add unapprove_agreement_for_countersignature method & accompanying test

dmapiclient/__init__.py, dmapiclient/data.py, setup.cfg, tests/test_apiclient.py
* New method `copy_brief` on `DataAPIClient`
* Tests
* Version bump
* add venvs to pep8 ignore
=> copy-my-requirements

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
=> Add get_audit_event

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
To support the addition of this filtering to the API - https://github.com/alphagov/digitalmarketplace-api/pull/600
=> Filter brief responses by framework slug

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_apiclient.py
Update APIClient according to [#596](https://github.com/alphagov/digitalmarketplace-api/pull/596)
=> Add earliest_for_each_object to audit event

.travis.yml, README.md, requirements-dev.txt
Matches the version we're using in production
=> Bump Travis python version to 3.6

dmapiclient/__init__.py, dmapiclient/audit.py
This is to support https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/740 and its story https://trello.com/c/V8bUSjq8/77-implement-an-email-sign-up-capability-for-suppliers-2
=> AuditTypes: add mailing_list_subscription event type

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
This includes the `user` filtering of `find_audit_events` and the addition of the `revert_service` method.
=> add tools for admin of service edits

dmapiclient/__init__.py, dmapiclient/audit.py
https://trello.com/c/0Q9fOz46/234-creating-a-supplier-is-not-audited-there-is-no-createsupplier-audit-event
=> Add `create_supplier` audit event

.gitignore, dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
Update update_user method to include user_research_preference
=> User research mailing list

dmapiclient/__init__.py, dmapiclient/audit.py
We don't currently have a specific audit event for this. In the api we
use `update_supplier` for some reason.
=> Add `update_supplier_framework` audit event

dmapiclient/__init__.py, dmapiclient/audit.py
Trello https://trello.com/c/4JtM91iv/67-create-back-end-interface-for-award-flow
=> Audit types: add three process outcome related audit types

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
Trello https://trello.com/c/N6Np8b1F/126-apiclient-additions-for-new-backend-endpoints
Striaghtforward enough right?
=> Add new outcome calls

dmapiclient/__init__.py, dmapiclient/antivirus.py, tests/test_antivirus_api_client.py
including support for `scan_and_tag_s3_object` endpoint.
This will be helpful when writing scripts.
=> add initial AntivirusAPIClient

dmapiclient/__init__.py, dmapiclient/audit.py
Trello: https://trello.com/c/aIsqTYgp/42-deleting-declaration-of-successful-suppliers
Adds a new AuditType for deleting a supplier's declaration.
=> New AuditType for deleting supplier declaration

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
https://trello.com/c/t2N1EqPk/
Sorry it's boring.
=> DataAPIClient: add find_outcomes method & tests 

default.nix, dmapiclient/__init__.py, dmapiclient/audit.py
https://trello.com/c/rMwWZyBv
What do people think? The kooky audit types around this area rather show their age, but this seems to fit best with them?
=> AuditTypes: add update_selection_questions 

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
https://trello.com/c/0ArURGlF
Not much more to say...
=> data api client: add update_supplier_declaration method 

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
To accompany https://github.com/alphagov/digitalmarketplace-api/pull/962 & https://trello.com/c/Vgh8eNG8
=> DataAPIClient.find_users: add user_research_opted_in argument 

dmapiclient/__init__.py, dmapiclient/data.py, requirements-dev.txt, tests/test_base_api_client.py, tests/test_data_api_client.py
https://trello.com/c/kCUjDnH4/48-3-3-jenkins-job-for-publish-services
API client method (and iterable method) for the new endpoint introduced in https://github.com/alphagov/digitalmarketplace-api/pull/1030.
=> New method for draft services by framework endpoint

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
https://trello.com/c/p8qUfLUA/
Corresponding API Client changes for https://github.com/alphagov/digitalmarketplace-api/pull/1049.
=> Bump version to 21.8.0

README.md
One is broken and one doesn't work as we have switched to Github Actions
=> remove unused badges

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
As added by https://github.com/alphagov/digitalmarketplace-api/pull/1089 and https://github.com/alphagov/digitalmarketplace-api/pull/1094
=> Support new API endpoints

.github/workflows/release.yml
https://trello.com/c/DrVWMkcZ/2169-rename-default-branches-on-our-repos-from-master-to-main
=> update branch used for releases

dmapiclient/__init__.py, dmapiclient/data.py, tests/test_data_api_client.py
This was added to the API recently: https://github.com/alphagov/digitalmarketplace-api/pull/1147. Add support to the API client.
Should make the service edit report easier.
=> Add support for sort_by to find_audit_events

dmapiclient/__init__.py, dmapiclient/data.py
added client endpoint  for supplier's agreement details for specific framework
=> added client endpoint for etl
